---
###########################
# Setup Kubernetes Cluster
###########################

- hosts: localhost
  connection: local
  environment:
    KOPS_STATE_STORE: s3://dev-k8s-demo
    cluster_name: demo.k8s.local
  tasks:
  - import_role: 
      name: lambda-delete
    tags: [use_lambda,never]
  - import_role: 
      name: lambda-install
    tags: [use_lambda,never]
  - set_fact:
      lambda_tags: true
    tags: [use_lambda,never]
  - import_role: 
      name: create-cluster
    tags: always
